export const ADD_MESSAGE = 'ADD_MESSAGE';
export const RECEIVE_MESSAGE = 'RECEIVE_MESSAGE';

export const ADD_CHANNEL = 'ADD_CHANNEL';
export const CHANGE_CHANNEL = 'CHANGE_CHANNEL';
export const RECEIVE_CHANNEL = 'RECEIVE_CHANNEL';

export const REGISTER_USER = 'REGISTER_USER';
export const LOGIN = 'LOGIN';

export const AUTH_LOAD = 'AUTH_LOAD';
export const AUTH_LOAD_SUCCESS = 'AUTH_LOAD_SUCCESS';
export const AUTH_LOAD_FAIL = 'AUTH_LOAD_FAIL';
export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAIL = 'AUTH_LOGIN_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_LOGOUT_SUCCESS = 'AUTH_LOGOUT_SUCCESS';
export const AUTH_LOGOUT_FAIL = 'AUTH_LOGOUT_FAIL';
export const AUTH_REGISTER_SUCCESS = 'AUTH_REGISTER_SUCCESS';
export const AUTH_REGISTER = 'AUTH_REGISTER';
export const AUTH_REGISTER_FAIL = 'AUTH_REGISTER_FAIL';

export const TYPING = 'TYPING';
export const STOP_TYPING = 'STOP_TYPING';

export const ADD_USER_TO_CHANNEL = 'ADD_USER_TO_CHANNEL';
export const REMOVE_USER_FROM_CHANNEL = 'REMOVE_USER_FROM_CHANNEL';

export const SAVE_USERNAME = 'SAVE_USERNAME';
