export const ADD_MESSAGE = 'ADD_MESSAGE';
export const RECEIVE_MESSAGE = 'RECEIVE_MESSAGE';

export const ADD_CHANNEL = 'ADD_CHANNEL';
export const CHANGE_CHANNEL = 'CHANGE_CHANNEL';
export const RECEIVE_CHANNEL = 'RECEIVE_CHANNEL';

export const SIGNUP_USER = 'SIGNUP_USER';
export const SIGNIN = 'SIGNIN';

export const AUTH_LOAD = 'AUTH_LOAD';
export const AUTH_LOAD_SUCCESS = 'AUTH_LOAD_SUCCESS';
export const AUTH_LOAD_FAIL = 'AUTH_LOAD_FAIL';

export const AUTH_SIGNIN = 'AUTH_SIGNIN';
export const AUTH_SIGNIN_SUCCESS = 'AUTH_SIGNIN_SUCCESS';
export const AUTH_SIGNIN_FAIL = 'AUTH_SIGNIN_FAIL';

export const AUTH_SIGNOUT = 'AUTH_SIGNOUT';
export const AUTH_SIGNOUT_SUCCESS = 'AUTH_SIGNOUT_SUCCESS';
export const AUTH_SIGNOUT_FAIL = 'AUTH_SIGNOUT_FAIL';

export const AUTH_SIGNUP_SUCCESS = 'AUTH_SIGNUP_SUCCESS';
export const AUTH_SIGNUP = 'AUTH_SIGNUP';
export const AUTH_SIGNUP_FAIL = 'AUTH_SIGNUP_FAIL';

export const TYPING = 'TYPING';
export const STOP_TYPING = 'STOP_TYPING';

export const ADD_USER_TO_CHANNEL = 'ADD_USER_TO_CHANNEL';
export const REMOVE_USER_FROM_CHANNEL = 'REMOVE_USER_FROM_CHANNEL';

export const SAVE_USERNAME = 'SAVE_USERNAME';

export const LOAD_MESSAGES = 'LOAD_MESSAGES';
export const LOAD_MESSAGES_SUCCESS = 'LOAD_MESSAGES_SUCCESS';
export const LOAD_MESSAGES_FAIL = 'LOAD_MESSAGES_FAIL';
