export const CLICK_THREAD = 'CLICK_THREAD';
export const CREATE_THREAD = 'CREATE_THREAD';
export const CREATE_MESSAGE = 'CREATE_MESSAGE';
export const RECEIVE_RAW_CREATED_MESSAGE = 'RECEIVE_RAW_CREATED_MESSAGE';
export const RECEIVE_RAW_MESSAGES = 'RECEIVE_RAW_MESSAGES';
export const ADD_MESSAGE = 'ADD_MESSAGE';
export const ADD_FRIEND = 'ADD_FRIEND';
